### ISSUE TITLE
Adding default support for other databases

### ISSUE THREAD

**Issue by samlobel** [buriburisuri/sugartensor#1]
First off, I really love this library. It makes tensorflow development so fast.

I wanted to make a plug for default support of CIFAR, like you have for MNIST. It's a real pain setting up the queue for CIFAR manually, and some image techniques only show their benefits on things more complex than MNIST.

I'd consider making a pull request for this, if you'd accept it

**Comment by buriburisuri** [comment]
Thank you for your interesting.

Pull requests are always welcome. I was thinking of adding CIFAR-10 and ImageNet dataset, and if you can help, it is welcome.

**Comment by samlobel** [comment]
Okay, I'll try my hand at it. Still enjoying the repo by the way, it's really great.
