### ISSUE TITLE
Setting bias to False

### ISSUE THREAD

**Issue by samlobel** [buriburisuri/sugartensor#3]
I could be misunderstanding this one, but does line 117 of sg_main mean that bias is always determined by either opt.bn or opt.ln? Is there a way to determine it explicitly?

**Comment by buriburisuri** [comment]
You can always determine explicitly.  

opt += tf.sg_opt(bias=not (opt.bn or opt.ln))  

'+=' operator in this line means default option injection.
If you provide bn or ln option, that will be used.  If not provided, this option will be used as defaults.

see https://github.com/buriburisuri/sugartensor/blob/master/sugartensor/sg_util.py.

Sorry again for the lack of document

**Comment by samlobel** [comment]
Okay, so you can explicitly set bias to False, correct?
Thank you again.
