### ISSUE TITLE
Adding Custom layers

### ISSUE THREAD

**Issue by aosokin** [buriburisuri/sugartensor#7]
Hi, this is a really amazing repo!
My question is again about custom layers.
What is the best way to add them?

**Comment by buriburisuri** [comment]
See issue #2

**Comment by aosokin** [comment]
As far as I under stand the by_pass layer that you are referencing is a part of sugartensor itself.
My question is a bit different: is there a way of adding a custom layer without touching the sugartensor code (say in file of my own script that imports sugartensor)?

**Comment by buriburisuri** [comment]
See the bytenet code example from the link in issue #2

**Comment by aosokin** [comment]
Works great! Thanks a lot!
